// <auto-generated />
namespace Teos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Conteudos_CamposCorLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conteudos_CamposCorLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201910010023028_Conteudos_CamposCorLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
