// <auto-generated />
namespace Teos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterarMembrosparaUsuarioeCriarentidadePapeis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterarMembrosparaUsuarioeCriarentidadePapeis));
        
        string IMigrationMetadata.Id
        {
            get { return "201910021835015_AlterarMembros-paraUsuario-e-Criar-entidade-Papeis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
