// <auto-generated />
namespace Teos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Conteudo_Hierarquia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conteudo_Hierarquia));
        
        string IMigrationMetadata.Id
        {
            get { return "201909301436504_Conteudo_Hierarquia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
