// <auto-generated />
namespace Teos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterarMembrosparaUsuarioeCriarentidadePapeisparte2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterarMembrosparaUsuarioeCriarentidadePapeisparte2));
        
        string IMigrationMetadata.Id
        {
            get { return "201910021841222_AlterarMembros-paraUsuario-e-Criar-entidade-Papeis-parte-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
