// <auto-generated />
namespace Teos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class conteudo_add_hierarquia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conteudo_add_hierarquia));
        
        string IMigrationMetadata.Id
        {
            get { return "201909301632569_conteudo_add_hierarquia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
